#########################################################################################
#
# Copyright (c) Microsoft Corporation. All rights reserved.
#
# Localized PSSwagger.Resources.psd1
#
#########################################################################################

ConvertFrom-StringData @'
###PSLOC

    ConvertingSwaggerSpecToGithubContent=Converting SpecificationUri to raw github content '{0}'
    SwaggerSpecDownloadedTo=Swagger spec from '{0}' is downloaded to '{1}'
    ExpandDefinition=Trying to expand the '{0}' defnition.
    UnableToExpandDefinition=Unable to expand the '{0}' definition in current iteration.
    UnapprovedVerb=Verb '{0}' not an approved verb.
    ReplacedVerb=Using Verb '{0}' in place of '{1}'.
    UsingCmdletNameForSwaggerPathOperation=Using cmdlet name '{0}' for Swagger path operationid '{1}'.
    GenerateCodeUsingAutoRest=Generating CSharp Code using AutoRest
    GenerateAssemblyFromCode=Generating assembly from the CSharp code
    GeneratedAssembly=Generated '{0}' assembly
    UnableToGenerateAssembly=Unable to generate '{0}' assembly
    InvalidSwaggerSpecification=Invalid Swagger specification file. Info section doesn't exists.
    SwaggerSpecPathNotExist=Swagger file $SwaggerSpecPath does not exist. Check the path
    SamePropertyName=Same property name '{0}' is defined in a definition '{1}' with AllOf inheritance.
    DataTypeNotImplemented=Please get an implementation of '{0}' for '{1}'
    AutoRestNotInPath=Unable to find AutoRest in PATH environment. Ensure the PATH is updated.
    CscExeNotInPath=Unable to find CSC.exe in PATH environment. Ensure the PATH is updated with CSC.exe location.
    IncorrectVersionOfCscExeInPath=The first CSC.exe in the PATH environment variable is the compiler included with Windows or the .NET framework. Please use the Microsoft.Net.Compilers package which contains the Roslyn CSC.exe, and ensure that package's CSC.exe comes first in your PATH environment variable.
    AutoRestError=AutoRest resulted in an error
    SwaggerParamsMissing=No parameters in the Swagger
    SwaggerDefinitionsMissing=No definitions in the Swagger
    SwaggerPathsMissing=No paths found in the Swagger document '{0}'.
    SkippingExistingParameter=Skipping an existing swagger parameter {0}.
    SkippingExistingKeyFromSwaggerMultiItemObject=Skipping an existing key '{0}' from SwaggerMultiItemObject.
    FoundFileWithHash=Found file '{0}' with hash '{1}'
    FoundPowerShellCoreMsi=Found MSI installation of PowerShell Core of version '{0}'
    MustSpecifyPsCorePath=No installations of PowerShell Core could be found. Please provide -PowerShellCorePath to specify the location of PowerShell Core.
    PsCorePathNotFound=Couldn't find PowerShell at path '{0}'
    ParameterSetNotAllowed=The '{0}' parameter is not allowed when '{1}' is specified.
    AssemblyCompilationResult=Result of assembly compilation: {0}
    CmdletHasAmbiguousParameterSets=The generated cmdlet '{0}' contains ambiguous parameter sets. This is due to automatic merging of two or more similar paths.
    PathNotFound=Cannot find the path '{0}' because it does not exist.
    GeneratedPathCommand=Generated path command '{0}'.
    GeneratedDefinitionCommand=Generated command '{0}' for the definition name '{1}'.
    GeneratedFormatFile=Generated output format file for the definition name '{0}'.
    FormatFileNotRequired=It is not required to generated the format file as this definition '{0}' doesn't have non-complex typed properties.
    DeleteGeneratedFile=Deleting generated file '{0}'
    ExtractingMetadata=Extracting metadata from generated assembly
    ExpectedServiceClientTypeNotFound=Unable to find expected service client type: {0}
    ExpectedOperationsClientTypeNotFound=Unable to find expected operations client property '{0}' on type '{1}'
    ExpectedMethodOnTypeNotFound=Unable to find expected method '{0}' on type '{1}'
    OptionalParameterNowRequired=The parameter '{0}' was marked as optional in the Swagger specification but required in generated code. Cmdlet '{1}' will require this parameter
    ReferenceTypeDefaultValueNotSupported=PSSwagger doesn't support setting a reference-type default value. Parameter: '{0}', Parameter Type: '{1}', Cmdlet: '{2}'
    ResultCodeMetadataExtraction=Result of code metadata extraction: {0}
    MetadataExtractFailed=Module generation failed. If no error messages follow, check the output of code metadata extraction above
    MultipleODataQueriesOneFunction=Multiple OData queries found in operation '{0}'. PSSwagger does not currently support this scenario.
    ParameterMissingFromAutoRestCode=Parameter '{0}' does not have a corresponding parameter in the autogenerated C# code and is not an ODataQuery parameter. Leaving this parameter out of the PowerShell cmdlet '{1}'
    UnsupportedSwaggerProperties='{0}' has unsupported properties. {1}
    GettingSwaggerSpecPathInfo=Getting details for Swagger path operation with operationid '{0}'.
    SuccessfullyGeneratedModule=Successfully generated module '{0}' at '{1}' for the specified Swagger specification.
    FlatteningParameterType=Flattening parameter '{0}' of type '{1}'
    ParameterExpandedTo=Parameter '{0}' was expanded to parameter '{1}'
    DuplicateExpandedProperty=Duplicate expanded property name: '{0}'
    InvalidPathParameterType=Extracted an invalid parameter type '{0}' for parameter '{1}' in path operation.
    InvalidDefinitionParameterType=Extracted an invalid parameter type '{0}' for parameter '{1}' in definition '{2}'.
    AutoRestParameterIgnored=The parameter '{0}' with value '{1}' specified in the Swagger specification will be overwritten by PSSwagger during code generation.
    InvokingAutoRestWithParams=Invoking AutoRest with the following parameters:
    AutoRestParam=  {0} = {1}
    OutputDirectoryMustBeEmpty=Code output directory '{0}' must not contain any .cs files in order for PSSwagger to correctly determine the files from which the SDK should be built.
    CustomNamespaceNotRecommended=Custom namespaces are not recommended when using PSSwagger, as the generated modules may not support side-by-side.
    CodeDirectoryWillBeCreated=Code output directory '{0}' will be created by AutoRest and contain unused generated code. You may delete this directory after the module has finished generating if you wish.
    MultiplePageReturnTypes=Multiple page return types found, unable to generate -Page parameter with a strong type for cmdlet '{0}'.
    FailedToFindPagingOperation=Failed to find specified next page operation with operationId '{0}' for cmdlet '{1}'.
    InvalidPagingOperationSchema=PSSwagger requires that the NextLink operation contains exactly one parameter different than the original operation, where the different parameter is used to pass the nextLink value to the NextLink operation. Current cmdlet: '{0}'. NextLink operation: '{1}'
    ParameterConflictAndResult=Parameter '{0}' from cmdlet '{1}' and parameter set '{2}' conflicts with an autogenerated parameter. {3}
    PagingNotFullySupported=As a result, full paging capabilities will not be supported.
    CredentialParameterNotSupported=As a result, the -Credential parameter of type PSCredential will not added, and the specification-specified parameter will be used instead.
    SecurityDefinitionsObjectMissing=Security object was specified in the Swagger specification, but the Security Definition object was not.
    SpecificSecurityDefinitionMissing=Security definition with name '{0}' is missing.
    SecurityDefinitionMissingProperty=API key security definition '{0}' is missing the '{1}' property.
    UnsupportedAuthenticationType=Authentication type '{0}' is not supported by PSSwagger. The generated module will default to no authentication unless overridden.
    MultipleSecurityTypesNotSupported=Multiple security requirements are currently unsupported. Only the first security requirement is being considered for command '{0}'.
    PSMetaFileExists=The PowerShell metadata file '{0}' already exists for the specified Swagger document '{1}'. Use -Force switch parameter to replace the existing metadata file '{0}'.
    SuccessfullyGeneratedMetadataFile=Successfully generated the PowerShell metadata file '{0}' for the specified Swagger specification '{1}'.
    NewPSSwaggerMetadataFileOperationMessage=Create PowerShell Swagger Metadata file
    ServiceTypeMetadataFileNotFound=The service type metadata file '{0}' does not exist.
    UnknownPSMetadataProperty=Unknown '{0}' property: '{1}'.
    InvalidPSMetaFlattenParameter=Flatten property is specified as 'true' for an invalid parameter '{0}' with type '{1}'.
    InvalidHeaderFileExtension=Header '{0}' file extension should be '.txt'.
    InvalidHeaderFilePath=The specified value '{0}' for Header parameter is should be a valid file path.
    HeaderContentTwoHyphenWarning=The specified Header content has '--', replacing '--' with '=='.
    PSScriptAnalyzerMissing=PSScriptAnalyzer specified as the formatter, but the module is not available on this machine. No formatting will be used. Run 'Install-Module -Name PSScriptAnalyzer -Repository PSGallery -Scope CurrentUser' to install the module.
    CouldntFindServerSideResultOperation=Couldn't find server-side result operation: {0}
    CouldntFindServerSideResultParameterSet=Couldn't find server-side result parameter set: {0}
    CouldntFindClientSideParameterSet=Couldn't find client-side parameter set: {0}
    MissingRequiredFilterParameter=Required server-side parameter '{0}' is not required by the client-side, which will cause issues in client-side filtering. Can't include client-side filtering.
    FailedToAddAutomaticFilter=Failed to add automatic client-side filter for candidate command '{0}': Mandatory List parameter '{1}' has no matching Get mandatory parameter. It will be impossible to guarantee execution of the List method before client-side filtering occurs.
    CopyingUtilityModule=Copying utility module to generated module
    ReSignUtilityModuleWarning=The local copy of the utility module at '{0}' should be signed or re-signed before distribution.
    TracingDisabled=Local utility module copies have service-level tracing disabled. This includes, but is not limited to, tracing what is sent and received from the service.
    CredentialsDisabled=Local utility module copies have built-in service credential types disabled.
###PSLOC
'@