version: 1.0.{build}
os:
    - Visual Studio 2017
configuration: Release
platform: Any CPU
install: 
    - cinst -y pester
build: off
test_script:
 - ps: |
        Push-Location  c:\projects\psswagger\Tests
        .\run-tests.ps1
        Pop-Location	 
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
 on_finish:
  - ps: |
    Get-ChildItem -Path .\Tests\ -Filter '*TestResults.xml' -File | ForEach-Object {
      (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", "$($_.FullName)")
    }