version: 1.0.{build}
os:
- WMF 5
configuration: Release
platform: Any CPU
install: 
    - cinst -y pester
build: off
test_script:
 - ps: >-
     & "c:\projects\psswagger\Tests\run-tests.ps1"
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))