version: 1.0.{build}
os:
    - Visual Studio 2017
configuration: Release
platform: Any CPU
install: 
    - cinst -y pester
    - ps: Install-Product node ''
    - npm install
    - node --version
    - npm --version
    - npm install -g autorest@1.1.0
    - autorest --reset
build: off
test_script:
 - ps: |
        Push-Location  c:\projects\psswagger\Tests
        .\run-tests.ps1 -EnableTracing -Verbose
        Pop-Location	 
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
on_finish:
    - ps: |
        Push-Location  c:\projects\psswagger\Tests
        .\Send-AppVeyorResults.ps1 -appVeyorUrl "https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)" -testResultRootDir c:\projects\psswagger -testResultFilePattern "*TestResults.xml" -generatedModulesDir c:\projects\psswagger\tests\Generated