<#
Code generated by Microsoft (R) PSSwagger 0.3.0
Changes may cause incorrect behavior and will be lost if the code is regenerated.
#>

Microsoft.PowerShell.Core\Set-StrictMode -Version Latest

<#
.DESCRIPTION
   Test wrapper for New-PSSwaggerClientTracing
#>
function Test-PSSwaggerUtilityFunction {
    [CmdletBinding()]
    param(
    )

    return New-PSSwaggerClientTracing
}

